# NeoForge mod metadata

modLoader="javafml"
loaderVersion="${loader_version_range}"

license="${mod_license}"

[[mods]]
modId="createbotr"
version="${mod_version}"
displayName="${mod_name}"

description='''
Jenny mod fr
'''

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
