# NeoForge mod metadata

modLoader="javafml"
loaderVersion="${loader_version_range}"

license="${mod_license}"

[[mods]]
modId="createbotr"
version="${mod_version}"
displayName="${mod_name}"

description='''
Jenny mod fr
'''

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.createbotr]]
modId="ae2"
type="required"
versionRange="[19.2.0,20.0.0)"
ordering="NONE"
side="BOTH"

[[dependencies.createbotr]]
modId="guideme"
type="required"
versionRange="[21.1.0,22.0.0)"
ordering="NONE"
side="BOTH"

[[dependencies.createbotr]]
modId="create_new_age"
type="required"
versionRange="[1.0.0,2.0.0)"
ordering="NONE"
side="BOTH"

[[dependencies.createbotr]]
modId="createaddition"
type="required"
versionRange="[1.0.0,2.0.0)"
ordering="NONE"
side="BOTH"

[[dependencies.createbotr]]
modId="powergrid"
type="required"
versionRange="[0.5.4,0.6.0)"
ordering="NONE"
side="BOTH"

[[dependencies.createbotr]]
modId="create"
type="required"
versionRange="[6.0.0,7.0.0)"
ordering="NONE"
side="BOTH"

[[dependencies.createbotr]]
modId="architectury"
type="required"
versionRange="[13.0.0,14.0.0)"
ordering="NONE"
side="BOTH"